name: Publish Base Python Image

on:
  push:
    tags:
      - 'v*'

jobs:
  build-publish-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Publish Default Python Image
        uses:  dagger/dagger-for-github@8.0.0
        with:
          version: "latest"
          module: github.com/munichbughunter/central-devsecops-pipeline
          args: build-default-python-image-and-publish --imageTag=${{ github.ref_name }} --githubUsername=munichbughunter --githubToken=env://${{ secrets.TOKEN }}