name: Trivy Scan

on:
  push:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set IMAGE_REF
        run: |
            if [ "${{ github.ref_type }}" = "tag" ]; then
                echo "IMAGE_REF=ghcr.io/munichbughunter/default-python:${{ github.ref_name }}" >> $GITHUB_ENV
            else
                echo "IMAGE_REF=ghcr.io/munichbughunter/default-python:latest" >> $GITHUB_ENV
            fi

      - name: Run Trivy via Dagger
        uses:  dagger/dagger-for-github@8.0.0
        env:
            GH_TOKEN: ${{ secrets.TOKEN }}
        with:
            version: "latest"
            module: github.com/munichbughunter/central-devsecops-pipeline
            args: scan-image --image-ref ${{ env.IMAGE_REF }} --github-username munichbughunter --github-token env://GH_TOKEN --output trivy-report.sarif

      - name: Upload SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-report.sarif'
